# Autogenerated by devscripts/update-version.py

__version__ = '2024.03.17.224823'

RELEASE_GIT_HEAD = 'f849d77ab54788446b995d256e1ee0894c4fb927'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'wangw469/yt-dlp'

ORIGIN = 'wangw469/yt-dlp'

_pkg_version = '2024.03.17.224823'
